//@version=5
indicator("Smart Support & Resistance Zones | Close Pivot + Wick Zone", overlay=true)

extend   = input.int(30, "Extend Right Bars")
lr       = input.int(10, "Left/Right Pivot Bars")
lookback = 2

var box resZone = na
var box supZone = na

// shared right side for alignment
var int sharedRight = na

// === Pivot detection based on CLOSE ===
ph_close = ta.pivothigh(close, lr, lr)
pl_close = ta.pivotlow(close, lr, lr)

// Pivot indexes
ph_index = ta.valuewhen(not na(ph_close), bar_index - lr, 0)
pl_index = ta.valuewhen(not na(pl_close), bar_index - lr, 0)

// update right side every bar
sharedRight := bar_index + extend

// ================= RESISTANCE ================= //
highestWick = ta.highest(high[lr - 1], lookback)
if not na(ph_close)
    resBottom = ph_close
    resTop = highestWick

    if na(resZone)
        resZone := box.new(int(ph_index), resTop, sharedRight, resBottom,
                           bgcolor = color.new(color.red, 70), border_color = color.red)
    else
        box.set_left(resZone, int(ph_index))
        box.set_top(resZone, resTop)
        box.set_bottom(resZone, resBottom)


// always align right side with shared value
if not na(resZone)
    box.set_right(resZone, sharedRight)


// ================= SUPPORT ================= //
lowestWick = ta.lowest(low[lr - 1], lookback)
if not na(pl_close)
    supTop = pl_close
    supBottom = lowestWick

    if na(supZone)
        supZone := box.new(int(pl_index), supTop, sharedRight, supBottom,
                           bgcolor = color.new(color.green, 70), border_color = color.green)
    else
        box.set_left(supZone, int(pl_index))
        box.set_top(supZone, supTop)
        box.set_bottom(supZone, supBottom)


// always align right side with shared value
if not na(supZone)
    box.set_right(supZone, sharedRight)
